-- delete all data from genre table
DELETE FROM movieDB.genre;
-- insert new data in genre table
INSERT INTO movieDB.genre (name) VALUES
	 ('Comedy'),
	 ('SCI-FI'),
	 ('Thriller'),
	 ('Horror'),
	 ('Action'),
	 ('Animation');

-- delete all data in movies table
DELETE  FROM movieDB.movie;
-- insert new data in  movies table
INSERT INTO movieDB.movie (description,name,rating,release_year,genre_id) VALUES
	 ('Hot Rod has brazen silliness and a few humorous set pieces on its side, but it''s far too inconsistent to satisfy all but the least demanding slapstick lovers.','Hot Rod',4,2007,1),
	 ('With a talented cast turned loose on a loaded premise -- and a sharp script loaded with dark comedy and unexpected twists -- Game Night might be more fun than the real thing.','Game Night',9,2018,1),
	 (' First Wives Club is headlined by a trio of comedic dynamos, but the script lets them down with tepid plotting and a fatal lack of satirical bite.','The First Wives Club',5,1996,1),
	 (' Critics say Scary Movie overloads on crudity and grossness to get its laughs.','Scary Movie',6,2000,1),
	 (' In this film, the matchless W. C. Fields plays Egbert Souse, a bibulous denizen of Lompoc who supports his family.','The Bank Dick',10,1940,1),
	 ('It’s probably best not to know too much about this sci-fi–inflected indie before you watch – though it’s okay to be aware ahead of time that director Charlie McDowell’s relationship dramedy doubles as a genre piece, and not just some run-of-the-mill story about a bickering married couple (played by Mark Duplass and Elisabeth Moss). There’s a big twist, which arrives after the spouses head off for a therapeutic weekend at a country estate. In a switcheroo worthy of The Twilight Zone, some supernatural mojo grants both husband and wife the opportunity to get exactly what they want from each other – provided that they’re willing to accept some dire consequences.','The One I Love',3,2014,2),
	 ('Evil extraterrestrials versus British hood rats – guess who wins? This funny, fast-paced sci-fi comedy (featuring future Force Awakens hero John Boyega and future female-Doctor-Who Jodie Whittaker) pits a bunch of neighborhood kids in a rough section of South London against an otherworldy invasion. And damned if their street smarts aren’t the only thing that stands between our species and total annihilation. The fact that it flips the script and makes the so-called underclass the heroes was reason enough to embrace this scrappy take on Eighties blockbusters, but it also brings its action and alien-scares A-game (those glowing teeth!) as well.','Attack the Block',5,2011,2),
	 ('Steven Spielberg was already toggling between his “serious movie” phase and his crowd-pleaser mode at the start
of the 21st century – and this tricky futuristic, hard sci-fi fable, which openly undercuts the optimism of E.T. and Close Encounters, attempts to balance both sides. Based on a Brian Aldiss short story that was one of the late Stanley Kubrick’s abandoned projects, A.I. tells the story of an ultra-realistic robot boy (played by Haley Joel Osment) who’s abandoned by his human masters and left to search the world to learn his purpose. At once dazzling and despairing, the film is a sprawling odyssey that asks what makes us human – and doesn’t offer many reassuring answers.','A.I. Artificial Intelligence',7,2001,2),
	 ('Don’t get too bogged down by the mechanics of the bizarre premise of this graphic-novel adaptation, in which the remnants of humanity struggle for survival aboard a speeding train in the wake of a global climate disaster. (A train, guys?) Just revel in this stylish, bizarre take on class warfare from South Korean director Bong Joon-ho (The Host, Okja), as revolutionary Curtis (Chris Evans) fights his way to the front of this hierarchical society on wheels, encountering homicidal schoolteachers, an army of axmen and a twisted prime minister (Tilda Swinton) along the way. Snowpiercer wears its strangeness and its singularity on its sleeve. Enjoy the ride. JS','Snowpiercer',9,2013,2),
	 ('Much like its impromptu dance scene, which launched a thousand glorious GIFs, writer-director Alex Garland’s movie is hypnotic, hip – and also profoundly unsettling. This gripping thriller twists the knife on one of sci-fi’s great themes – what it means to be human – by placing mortals and androids in the same confined space and then consistently shifting our sympathies. Alicia Vikander electrifies as the seductive, seemingly subservient robot that slowly gets under the skin of the male programmers (Domhnall Gleeson, Oscar Isaac) who are under the mistaken impression that they’re studying her … and not the other way ’round. A relatively low-budget film that nonetheless walked off with the Best Visual Effects Oscar, Ex Machina is a marvel of smarts over spectacle, dissecting sexism and power dynamics with a cold-blooded efficiency worthy of its steely heroine. TG','Ex Machina',10,2014,2);
INSERT INTO movieDB.movie (description,name,rating,release_year,genre_id) VALUES
	 ('Greta is a 2018 psychological thriller film which really gives us the heebie jeebies.

It stars Isabelle Huppert (who plays a lonely widow named Greta) and Chloë Grace Moretz (a young woman named Frances) who become friends. That is, until Greta becomes obsessed with Frances (and we mean really obsessed). When Frances tries to end the creepy relationship, Greta takes things into her own hands. ','Greta',10,2018,3),
	 ('Steve McQueen''s crime heist thriller documents three recently widowed women (played by Viola Davis, Michelle Rodriguez and Elizabeth Debicki) who attempt to execute the heist their late husbands were planning. Also starring Cynthia Erivo, Colin Farrell and Daniel Kaluuya, this is not one to be missed.','Widows',8,2018,3),
	 ('best thriller movies YouTube Thriller movies are reserved for the most fearless of movie fanatics. Rather than the blood and gore of many horror films, thrillers are full of conflict, unexpected twists and tensions that have you on the edge of your seats. Better yet, the anxiety, terror and uncertainty inflicted on a viewer by thrillers can force them to question themselves, their close ones and even their own reality. From 2020 Oscar winner Parasite, which delves into the subjects of greed and class, to Rosamund Pike’s scene-stealing performance in psychological thriller Gone Girl, the best thrillers are the ones that seem so real they give us nightmares. That’s why we’ve rounded up a list of the best thriller movies to watch that are sure to have you biting your nails throughout.','Blood Diamond',7,2006,3),
	 ('best thriller movies YouTube Thriller movies are reserved for the most fearless of movie fanatics. Rather than the blood and gore of many horror films, thrillers are full of conflict, unexpected twists and tensions that have you on the edge of your seats. Better yet, the anxiety, terror and uncertainty inflicted on a viewer by thrillers can force them to question themselves, their close ones and even their own reality. From 2020 Oscar winner Parasite, which delves into the subjects of greed and class, to Rosamund Pike’s scene-stealing performance in psychological thriller Gone Girl, the best thrillers are the ones that seem so real they give us nightmares. ','Bird Box',5,2018,3),
	 ('The only reason we don’t like fava beans and chianti is thanks to this multi-Oscar winning thriller starring Jodie Foster and Anthony Hopkins.

In the film, Foster’s character Clairce Sterling is an FBI student who goes to interview Dr Hannibal Lecter (Hopkins), who is a psychiatrist and psychopath serving time for murder and cannibalism. In exchange for his thoughts on a high-profile case, Lecter asks to be moved to a more comfortable facility and begins to dig into Sterling’s past, making her a prime target for his wicked ways.','Silence Of The Lambs',4,1991,3),
	 ('After a space merchant vessel receives an unknown transmission as a distress call, one of the crew is attacked by a mysterious life form and they soon realize that its life cycle has merely begun.','Alien',9,1979,4),
	 ('A grieving family is haunted by tragic and disturbing occurrences.','Hereditary',8,2018,4),
	 ('On the trail of a missing girl, an ex-cop comes across a secretive group attempting to summon a terrifying supernatural entity.','The Empty Man',6,2020,4),
	 ('An imprisoned vampire, Barnabas Collins, is set free and returns to his ancestral home, where his dysfunctional descendants are in need of his protection.','Dark Shadows',7,2012,4),
	 ('A family in 1630s New England is torn apart by the forces of witchcraft, black magic, and possession.','The Witch',7,2015,4);
INSERT INTO movieDB.movie (description,name,rating,release_year,genre_id) VALUES
	 ('Determined to ensure Superman''s ultimate sacrifice was not in vain, Bruce Wayne aligns forces with Diana Prince with plans to recruit a team of metahumans to protect the world from an approaching threat of catastrophic proportions.',' Zack Snyder''s Justice League ',8,2021,5),
	 ('MMA fighter Cole Young seeks out Earth''s greatest champions in order to stand against the enemies of Outworld in a high stakes battle for the universe.',' Mortal Kombat',7,2021,5),
	 ('The world is beset by the appearance of monstrous creatures, but one of them may be the only one who can save humanity.','Godzilla ',6,2014,5),
	 ('In a future where the polar ice-caps have melted and Earth is almost entirely submerged, a mutated mariner fights starvation and outlaw "smokers," and reluctantly helps a woman and a young girl try to find dry land.','Waterworld ',6,1995,5),
	 ('Fearing that the actions of Superman are left unchecked, Batman takes on the Man of Steel, while the world wrestles with what kind of a hero it really needs.','Batman v Superman: Dawn of Justice',6,2016,5),
	 ('Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.','The Lion King',9,1994,6),
	 ('During her family''s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.',' Spirited Away',9,2001,6),
	 ('A look at the life of Jiro Horikoshi, the man who designed Japanese fighter planes during World War II.','The Wind Rises',8,2013,6),
	 ('A special bond develops between plus-sized inflatable robot Baymax and prodigy Hiro Hamada, who together team up with a group of friends to form a band of high-tech heroes.','Big Hero 6',8,2014,6),
	 ('A family of undercover superheroes, while trying to live the quiet suburban life, are forced into action to save the world.','The Incredibles ',8,2004,6);